name: sonarcloud analysis
on:
  push:
    branches: [master]
jobs:
  use-reusable-workflow:
    uses: honeybadgersoftware/ci-cd/.github/workflows/on-push-sonar.yml@master
    with:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      gh_token: ${{ secrets.GH_TOKEN }}